export const CUST_SIGNIN_REQUEST = "CUST_SIGNIN_REQUEST";
export const CUST_SIGNIN_SUCCESS = "CUST_SIGNIN_SUCCESS";
export const CUST_SIGNIN_FAIL = "CUST_SIGNIN_FAIL";
export const CUST_SIGNOUT = "CUST_SIGNOUT ";

export const CUST_FUND_TRANS_REQUEST = "CUST_FUND_TRANS_REQUEST";
export const CUST_FUND_TRANS_SUCCESS = "CUST_FUND_TRANS_SUCCESS";
export const CUST_FUND_TRANS_FAIL = "CUST_FUND_TRANS_FAIL";

export const CUST_CHANGE_MOB_REQUEST = "CUST_CHANGE_MOB_REQUEST";
export const CUST_CHANGE_MOB_SUCCESS = "CUST_CHANGE_MOB_SUCCESS";
export const CUST_CHANGE_MOB_FAIL = "CUST_CHANGE_MOB_FAIL";

export const CUST_CHANGE_PASS_REQUEST = "CUST_CHANGE_PASS_REQUEST";
export const CUST_CHANGE_PASS_SUCCESS = "CUST_CHANGE_PASS_SUCCESS";
export const CUST_CHANGE_PASS_FAIL = "CUST_CHANGE_PASS_FAIL";

export const CUST_CHANGE_EMAIL_REQUEST = "CUST_CHANGE_EMAIL_REQUEST";
export const CUST_CHANGE_EMAIL_SUCCESS = "CUST_CHANGE_EMAIL_SUCCESS";
export const CUST_CHANGE_EMAIL_FAIL = "CUST_CHANGE_EMAIL_FAIL";

export const CUST_REGISTER_REQUEST = "CUST_REGISTER_REQUEST";
export const CUST_REGISTER_SUCCESS = "CUST_REGISTER_SUCCESS";
export const CUST_REGISTER_FAIL = "CUST_REGISTER_FAIL";

export const CUST_TRANS_LIST_REQUEST = "CUST_TRANS_LIST_REQUEST";
export const CUST_TRANS_LIST_SUCCESS = "CUST_TRANS_LIST_SUCCESS";
export const CUST_TRANS_LIST_FAIL = "CUST_TRANS_LIST_FAIL";
export const CUST_NEW_CUST_REQUEST="CUST_NEW_CUST_REQUEST";
export const CUST_NEW_CUST_FAIL="CUST_NEW_CUST_FAIL";
export const CUST_NEW_CUST_SUCCESS="CUST_NEW_CUST_SUCCESS";
