export const ADMIN_SIGNIN_REQUEST = "ADMIN_SIGNIN_REQUEST";
export const ADMIN_SIGNIN_SUCCESS = "ADMIN_SIGNIN_SUCCESS";
export const ADMIN_SIGNIN_FAIL = "ADMIN_SIGNIN_FAIL";
export const ADMIN_SIGNOUT = "ADMIN_SIGNOUT ";

export const ADMIN_ADD_CUST_REQUEST = "ADMIN_ADD_CUST_REQUEST";
export const ADMIN_ADD_CUST_SUCCESS = "ADMIN_ADD_CUST_SUCCESS";
export const ADMIN_ADD_CUST_FAIL = "ADMIN_ADD_CUST_FAIL";
export const ADMIN_ADD_CUST_RESET = "ADMIN_ADD_CUST_RESET ";

export const CUST_LIST_REQUEST = "CUST_LIST_REQUEST";
export const CUST_LIST_SUCCESS = "CUST_LIST_SUCCESS";
export const CUST_LIST_FAIL = "CUST_LIST_FAIL";

export const TRANS_LIST_REQUEST = "TRANS_LIST_REQUEST";
export const TRANS_LIST_SUCCESS = "TRANS_LIST_SUCCESS";
export const TRANS_LIST_FAIL = "TRANS_LIST_FAIL";
